swagger: "2.0"

info:
  version: "1.0"
  title: "SecretSanta"
  description: "Create your own Secret Santa!"

host: "uaas070120252.appspot.com"
basePath: "/api/v1"

schemes:
  - https

paths:
  /clean:
    get:
      description: "Clean the database"
      operationId: "CleanDB"
      responses:
        200: 
          description: "Ok"
          
  /santa/{email}:
    parameters:
      - name: email
        in: path
        required: true
        description: "Email address of the Secret Santa participant"
        type: string
        format: email
    post:
      description: "Add a particpant to the Secret Santa"
      operationId: "santaPost"
      consumes:
        - application/json
      parameters:
        - in: body
          name: SantaParticpant
          required: True
          description: "Configuration and details of the Secret Santa participation"
          schema:
            $ref: "#/definitions/SantaParticpant"
      responses:
        201:
          description: "Success"
          schema:
            $ref: "#/definitions/SantaParticpant"
        400:
          description: "Generic error"
        409:
          description: "Conflict"
    get:
      description: "Get receiver of the gift"
      operationId: "santaGet"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/SantaExtraction"
        400:
          description: "Generic error"
        404:
          description: "Not Found"

definitions:
  SantaParticpant:
    type: object
    required:
      - firstName
      - lastName
    properties:
      firstName: 
        type: string
      lastName: 
        type: string
    example:
      firstName: "Riccardo"
      lastName: "Lancellotti"
  SantaExtraction:
    type: object
    required:
      - fromEmail
      - fromFirstName
      - fromLastName
      - toEmail
      - toFirstName
      - toLastName
    properties:
      fromEmail:
        type: string
      fromFirstName:
        type: string
      fromLastName:
        type: string
      toEmail:
        type: string
      toFirstName:
        type: string
      toLastName:
        type: string
    example:
      fromEmail: "riccardo.lancellotti@unimore.it"
      fromFirstName: "Riccardo"
      fromLastName: "Lancellotti"
      toEmail: "mirco.marchetti@unimore.it"
      toFirstName: "Mirco"
      toLastName: "Marchetti"


